default_context:
  project_name: 'Doctor Assistant'
  project_slug: 'DoctorAssistant'
  domain_main: 'DoctorAssistant.com'
  domain_staging: 'stag.DoctorAssistant.com'
  docker_swarm_stack_name_main: 'DoctorAssisant-com'
  docker_swarm_stack_name_staging: 'stag-doctorAssistant-com'
  secret_key: 'e6de2326bb0c17772ffe16cf4b2757461d30c30640b90eecf2a7a714ddee13a0'
  first_superuser: 'admin'
  first_superuser_password: '123456789'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.DoctorAssistant.com", "https://stag.DoctorAssistant.com", "https://DoctorAssistant.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'localhost'
  smtp_user: 'admin'
  smtp_password: '123456789'
  smtp_emails_from_email: 'info@DoctorAssistant.com'
  postgres_password: '123456789'
  pgadmin_default_user: 'SA'
  pgadmin_default_user_password: '123456789'
  traefik_constraint_tag: 'doc_assistnt_v1'
  traefik_constraint_tag_staging: 'stag.DoctorAssistant.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:123456789'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
